### ISSUE TITLE
about acloud update

### ISSUE THREAD

**Issue by ghost** [AlessioCasco/AWS-CSA-2019-study-notes#1]
has acloud team updated the udemy course as well?

**Comment by AlessioCasco** [comment]
Hi! 
It seems they haven't yet, my feeling is that they will keep the new version exclusively for themselves for a while before updating udemy. I also strongly believe (haven't checked the new course yet) that the content and/or material of the new course have not many differences from the old one.

**Comment by ghost** [comment]
Thanks for the information. I am planning to buy the course from udemy by this guy and also dolfined aws course which is a bit more expensive.
