### ISSUE TITLE
some typos

### ISSUE THREAD

**Issue by ghost** [AlessioCasco/AWS-CSA-2019-study-notes#3]
i think there are some typos like this one from s3 section
S3 is a universal namespace, the name must be unique globally. So you can have the same name as someone else.

should it not be cannot have same name here?

**Comment by nexmo-ops** [comment]
Hi!
Thanks for reporting that, you are right, you **can't** have bucket names having the same name as someone else.
Will fix it :bowing_man:

**Comment by AlessioCasco** [comment]
Hi!
Thanks for reporting that, you are right, you can't have bucket names having the same name as someone else. 
Will fix it thanks! :bowing_man:
