### ISSUE TITLE
What's wrong with our Practice Tests?

### ISSUE THREAD

**Issue by jsbonso** [AlessioCasco/AWS-CSA-2019-study-notes#8]
Thank you for mentioning our practice tests. Would appreciate it if you can share the specific items that you think are not helpful and misleading. This will help us to fix those problems in the future.

You mentioned:

> Purchased the AWS Certified Solutions Architect Associate Practice Exams by Jon Bonso but personally found not very helpful and sometimes misleading. Some questions are very different from the exam and sometimes wrong questions can be actually true.

Our reviewer is not an exam dump which is why you will never see the exact same question/scenario in the actual AWS exam.

Looking forward to your reply @AlessioCasco

**Comment by jsbonso** [comment]
And update on this @AlessioCasco?

**Comment by AlessioCasco** [comment]
Hello, sorry for my late on this.

It's been a while since the exam but from what I remember, your test questions where very different from what the exam looks like in reality. I know that the questions won't be the same as the one you will find in the exam, that's impossible, but I felt that they were different in the structure and also in the way AWS wants you to think during the exam.

I was initially doing the test questions acloudguru had in his course and I can say that those were more similar to what the real exam looks like, of course, no one is perfect and they are not an exception. 

As I mentioned on the Readme, it's a personal opinion and looking at your course score 4.4 (1,949 ratings) it's indeed an amazing project, sorry it didn't work out for me :-)

Hope this helped a bit, happy to discuss further.

Alessio

**Comment by jsbonso** [comment]
Hi Alessio,

Glad you finally replied. Before I begin, I just want to greet you and your family a happy new year. You said: 

> looking at your course score 4.4 (1,949 ratings) 

That is quite incorrect. It seems that you are talking about a **different** Udemy course since the numbers are way, way off. My AWS Certified Solutions Architect Practice Tests in Udemy has 4.6 (9,452 ratings) with over 50,000 students. I don't understand how you've made that number up, as the link to my course in your repo is correct:

https://www.udemy.com/course/aws-certified-solutions-architect-associate-amazon-practice-exams/ 


I respect your opinion but when you threw a false accusation that my course is just 4.4 (1,939 ratings), on a public Github repo like this, I somehow suspect that you made a mistake and was actually referring to another course. 

I also checked our student records in Udemy who bought our SAA practice tests course and it seems that you bought it last April 9, 2019 but didn't complete all of our 6 sets. You refunded our course on Apr 11, 2019 which is **just 2 days after.** 
 
In your github repo, your opinion of my course is:

> Some questions are very different from the exam and sometimes wrong questions can be actually true.

All of our questions have corresponding links to the actual AWS documentation to support our answers. I suspect that you didn't even have the time to read all of our detailed documentation because you just used our product for merely 2 days. Again, I respect your opinion if you think that the answers I provided are incorrect. It's just sad that you weren't able to post it in our QA discussion board so we can further talk about it and verify who is really correct. 

I don't know if you can still remember the wrong scenarios that you saw in our practice tests last April. If you can share them, then it would be great so we can further discuss. I am taking your word: _"happy to discuss further"_ literally here, haha :)

I have made a lot of successful pull-requests to the actual AWS documentation. I like to discuss technical things and if something is incorrect, then let's talk and find a way to solve it.  I acknowledge that my course is not perfect so I am keen on always improving it (as you can see in our course updates). 

There are some advanced AWS concepts that you may think is correct, but in reality, it is not. Sometimes, the official AWS documentation is not updated or needs to be rectified. As proof, here are the ones I've raised:

https://github.com/awsdocs/iam-user-guide/pull/57
https://github.com/awsdocs/amazon-ec2-user-guide/pull/37
https://github.com/awsdocs/amazon-ec2-user-guide/pull/45
https://github.com/awsdocs/aws-snowball-developer-guide/pull/1
https://github.com/awsdocs/aws-cost-management-user-guide/pull/20

Looking forward to your reply so we can discuss the topics that you think that I have provided wrong. If you can't, then your opinion is just unsubstantiated (in my opinion) and can be refuted based on the data I've provided above. If I can give this level of detail in my response, you can be sure that the products I made are of the same quality as well, with proper documentation/records to support my answer.

I hope I won't wait for yet another few months again for a response 👍 

Best Regards,
Jon Bonso

**Comment by AlessioCasco** [comment]
Hello

> That is quite incorrect. It seems that you are talking about a different Udemy course since the numbers are way, way off. My AWS Certified Solutions Architect Practice Tests in Udemy has 4.6 (9,452 ratings) with over 50,000 students

I agree here, there must be a mistake in the course I checked when copying the rating from, now it's even higher, 4.6 (13,058 ratings). I'm sorry for this, was absolutely not my intention to write wrong information.

> All of our questions have corresponding links to the actual AWS documentation to support our answers. 

I'm not saying that all the questions were wrong, I may have got some ones that may have been flagged incorrectly, mistakes can happen and I'm sorry if I didn't flag or report them so you could review and fix them if needed. As mentioned on the README, a lot of the questions that I encountered from your course were very different (in terms of how they were structured and how they were asked) compared to the ones I got in my exam, at least this is what happened to me.

Best 
Alessio
